### ISSUE TITLE
Can't save API key

### ISSUE THREAD

**Issue by wassimk** [devmynd/harbor#19]
I just installed with `brew`. I go in to set my API key and refresh rate but the save option is never available.

![2016-09-14_09-18-04](https://cloud.githubusercontent.com/assets/2261839/18515808/407b7010-7a5c-11e6-887b-66a3b33c27ab.png)

**Comment by jhirn** [comment]
Sorry you are having this issue. We have seen this in the past can you tell us what version of OSX you're running.

**Comment by wassimk** [comment]
No worries! Cool app so I just want to get it 👍 .

![image](https://cloud.githubusercontent.com/assets/2261839/18592706/c429914c-7bfd-11e6-8d08-f38c9ee4b1ad.png)

**Comment by adamtester** [comment]
I am having the same issue
![screen shot 2016-09-16 at 6 39 55 pm](https://cloud.githubusercontent.com/assets/2249484/18595515/fe8b7b22-7c3c-11e6-99da-0abc11eca1f1.png)

**Comment by tycobbb** [comment]
Fixed by 12daf97.

We just pushed up a release that includes this and other bug fixes. You should be good to go after a quick reinstall!
