### ISSUE TITLE
Archive Project

### ISSUE THREAD

**Issue by Vad1mo** [devmynd/harbor#24]
Hey,

we would like to use the name Harbor for the official CNCF [Harbor](https://goharbor.io/) [CLI](https://github.com/goharbor/harbor-cli).  

Currently, this project is using this name. 
So you probably need to archive this name and announce the deprecation, since it isn't used and working anymore.
https://formulae.brew.sh/cask/harbor#default

**Comment by darcygarrett** [comment]
We submitted a PR to remove Harbor cask, submitted here: https://github.com/Homebrew/homebrew-cask/pull/168305
